# Generated by Django 2.0.2 on 2018-05-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truecaller',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
